# syntax=docker/dockerfile:1

# Use the specified Python version
ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-alpine as base

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create a non-privileged user
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

# Copy the source code into the container
ADD https://github.com/Lickitysplitted/scaling-winner.git#main:app/hello_world /app


# Set working directory
WORKDIR /app/hello_world

# Set proper ownership of the application files
RUN chown -R appuser:appuser /app

# Switch to the non-privileged user to run the application
USER appuser

# Run the application
CMD python -u hello_world.py